name: aiida-phonopy-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - aiida-core~=2.3.0,!=2.7.0
  - xmltodict
  - jupyterlab=3
  - jupyterlab-myst
  - cryptography>=37.0.4  # lower gives wrong link to openssl
  - nglview=3
  # see: https://github.com/nglviewer/nglview/issues/1032
  - ipywidgets<8
  # documentation
  - myst-parser~=3.0.0
  - myst-nb~=1.0
  - sphinx-design
  - sphinx-book-theme
  - sphinx-subfigure>=0.2.4
  - seekpath
